name:                haskellator
version:             0.1.0.0
github:              "JoyOfHardware/haskellator"
license:             none
author:              "JoyOfHardware"
maintainer:          "joyofhardware@github.com"
copyright:           "2024 JoyOfHardware"

extra-source-files:
- README.md
- CHANGELOG.md
data-files:
- test/corpus/*

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/JoyOfHardware/haskellator#readme>

default-extensions:
- LambdaCase
- TupleSections
- ViewPatterns

dependencies:
- base >= 4.7 && < 5
- filepath
- text
- prettyprinter
- attoparsec

ghc-options:
- -Wall
- -O2
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  rtlil-parse:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskellator

tests:
  haskellator-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskellator
    - tasty
    - tasty-golden
    - directory
